services:
  llama-server:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: llama-server
    ports:
      - "8081:8080"
    volumes:
      - ./llama.cpp:/app/llama.cpp
    restart: always

  ui:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: beeswarm_model_api
    restart: always
    ports:
      - "8082:8080"
    environment:
      API: ${API:-beeswarm}

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: beeswarm_model_api
    restart: always
    ports:
      - "8082:8080"
    environment:
      API: ${API:-beeswarm}

#   postgres:
#     image: postgres:15
#     container_name: beeswarm_database
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER:-beeswarm}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB:-beeswarm}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U beeswarm -d beeswarm"]
#       interval: 5s
#       retries: 5

# volumes:
#   postgres_data:
