services:
  ui:
    image: beeswarm_lb
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    container_name: beeswarm_ui
    ports:
      - "8600:3000"
    restart: always
    mem_limit: 1g
    cpus: "2.0"
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 10.177.195.1
      - 213.186.33.99

  api:
    image: beeswarm_lb_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: beeswarm_api
    ports:
      - "8601:8080"
    restart: always
    env_file: .env
    mem_limit: 1g
    cpus: "2.0"
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 10.177.195.1
      - 213.186.33.99

  postgres:
    image: postgres:15
    container_name: beeswarm_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-beeswarm}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-beeswarm}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beeswarm -d beeswarm"]
      interval: 5s
      retries: 5
    mem_limit: 1g
    cpus: "2.0"
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 10.177.195.1
      - 213.186.33.99

volumes:
  postgres_data:
